language: ruby

rvm:
- 2.2.4

before_install:
- nvm install 7.9
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
- rm -rf google-chrome*.deb

script: ./scripts/travis.sh

sudo: required
dist: trusty

cache:
  directories:
  - /usr/bin

addons:
  sauce_connect: true

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - SAUCE_BROWSER_NAME="chrome"
  - SAUCE_BROWSER_VERSION=""
  - SAUCE_PLATFORM="Windows 10"
  - SAUCE_APPIUM_VERSION=""
  - SAUCE_DEVICE_NAME=""
  - SAUCE_DEVICE_ORIENTATION=""
  - SAUCE_PLATFORM_VERSION=""
  - SAUCE_PLATFORM_NAME=""
  - secure: RW99TW7YvGgWt/P8fQQziPbxNITaJMO/4q2iCX72u/PtTu2dkeaCqUiRUi7qyV8jIIk7U4oruxJRFQpTaCIX5+JWZsSwLskoTsspOI9aTzyPdhVNckM1vpA5VfwstdyQTkX7zzKPLdvXK0xj0ZzQ+ACH/SobQNYKiAMvW7FVkIc=
  - secure: gFSORYQLSBNIK8peGgUOhd0Yj6GzE18HA0GLrmp0PMtobe003poalkNgLsPy2W2QFZbG3bCjbqFMmCbUh5uRnX8eCy/whe+lwXeQsv5uh0EIGWgxVxhk79dCx5cakERusoj2BUgJJ432R7nRXjEW5v2AK9QAOeCG2Dvwdb8WSes=
